name: "Test Github Action"
description: "A Github that im currently using as a test platform"
branding:
  icon: sliders
  color: purple
inputs:
  name:
    description: 'The repository name. Example, "samples".'
    required: true
outputs:
  summary-title:
    description: "The title of the code metrics action."
  summary-details:
    description: "A detailed summary of all the projects that were flagged."
  updated-metrics:
    description: "A boolean value, indicating whether or not the CODE_METRICS.md was updated as a result of running this action."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-n"
    - ${{ inputs.name }}
