# The name of the work flow. Badges will use this name
name: "Test Github workflow"

on:
  push:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run
        run: dotnet run --project GithubAction

      - name: Run custom Github action
        id: dotnet-custom-action
        uses: Timmoth/github-data@main
        with:
          name: ${{ github.repository }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: new pr commit-message
          title: new pr title
          body: new pr body
          branch: main
          base: github-action-branch
