# The name of the work flow. Badges will use this name
name: "Test Github workflow"

on:
  push:
    branches: [main]
    paths:
      - "GithubAction/GithubAction/**" # run on all changes to this dir
      - "!GithubAction/GithubAction/CODE_METRICS.md" # ignore this file
  workflow_dispatch:
    inputs:
      reason:
        description: "I manually started the workflow"
        required: true
        default: "Manual run"

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Run custom Github action
        id: dotnet-custom-action
        uses: Timmoth/github-data@main
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          dir: ${{ './GithubAction/GithubAction' }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        if: ${{ steps.dotnet-code-metrics.outputs.updated-metrics }} == 'true'
        with:
          title: "${{ steps.dotnet-code-metrics.outputs.summary-title }}"
          body: "${{ steps.dotnet-code-metrics.outputs.summary-details }}"
          commit-message: ".NET code metrics, automated pull request."
